//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UventaApp.Resources.Dictionarys
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UventaArendaEntities : DbContext
    {
        public UventaArendaEntities()
            : base("name=UventaArendaEntities")
        {
        }
        private static UventaArendaEntities _context;
        public static UventaArendaEntities getContext()
        {
            if(_context == null)
            {
                _context = new UventaArendaEntities();
            }return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Building> Building { get; set; }
        public virtual DbSet<Rent> Rent { get; set; }
        public virtual DbSet<RentalObject> RentalObject { get; set; }
        public virtual DbSet<RentalType> RentalType { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Tenant> Tenant { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
